server:
  port: 8080

spring:
  application:
    name: quiz-leaderboard
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    com.quiz: INFO
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX}","level":"%level","thread":"%thread","logger":"%logger{36}","message":"%msg","regNo":"%X{regNo:-}"}%n'
